#!/bin/sh
set -e

case "$1" in
        configure)
		# Migrating firmware to new format
		if apt list --installed | grep -q qcom-x1e-firmware-extracted/
		then
			qcom-firmware-extract -d /lib/firmware/qcom/x1e80100
		fi
                ;;
esac

#DEBHELPER#

exit 0
